### PR TITLE
COMP: Update VMTK to fix packaging of Python libraries on macOS

### LINKED ISSUE #37: VMTK gone missing recently on macOS in Slicer-4.11.20210226 and latest Slicer-4.13
The extension installation package does not contain VMTK binaries, only the Slicer module .py files, for both latest Slicer Stable Release and Slicer Preview Release on macOS.

It seems that the recent upgrade to VTK9 broke packaging for VTK-8.2.

### PR DESCRIPTION
**Pull request by jcfr**
List of changes:

```
$ git shortlog 671b54d..ca83ce1 --no-merges
Jean-Christophe Fillion-Robin (1):
      COMP: Fix packaging of Python libraries on macOS
```

Fixes #37

### CODE REVIEW

**Comment by jcfr** [comment]
Local testing confirm the library are packaged on macOS:

```
$ cd _CPack_Packages/Darwin/TGZ/30230-macosx-amd64-SlicerVMTK-gite73746c-2021-09-12
$ find . | grep "Python\."

./_CPack_Packages/Darwin/TGZ/30230-macosx-amd64-SlicerVMTK-gite73746c-2021-09-12/Slicer.app/Contents/Extensions-30230/SlicerVMTK/lib/Slicer-4.13/qt-loadable-modules/vtkvmtkCommonPython.so
./_CPack_Packages/Darwin/TGZ/30230-macosx-amd64-SlicerVMTK-gite73746c-2021-09-12/Slicer.app/Contents/Extensions-30230/SlicerVMTK/lib/Slicer-4.13/qt-loadable-modules/vtkvmtkComputationalGeometryPython.so
./_CPack_Packages/Darwin/TGZ/30230-macosx-amd64-SlicerVMTK-gite73746c-2021-09-12/Slicer.app/Contents/Extensions-30230/SlicerVMTK/lib/Slicer-4.13/qt-loadable-modules/vtkvmtkDifferentialGeometryPython.so
./_CPack_Packages/Darwin/TGZ/30230-macosx-amd64-SlicerVMTK-gite73746c-2021-09-12/Slicer.app/Contents/Extensions-30230/SlicerVMTK/lib/Slicer-4.13/qt-loadable-modules/vtkvmtkIOPython.so
./_CPack_Packages/Darwin/TGZ/30230-macosx-amd64-SlicerVMTK-gite73746c-2021-09-12/Slicer.app/Contents/Extensions-30230/SlicerVMTK/lib/Slicer-4.13/qt-loadable-modules/vtkvmtkITKPython.so
./_CPack_Packages/Darwin/TGZ/30230-macosx-amd64-SlicerVMTK-gite73746c-2021-09-12/Slicer.app/Contents/Extensions-30230/SlicerVMTK/lib/Slicer-4.13/qt-loadable-modules/vtkvmtkMiscPython.so
./_CPack_Packages/Darwin/TGZ/30230-macosx-amd64-SlicerVMTK-gite73746c-2021-09-12/Slicer.app/Contents/Extensions-30230/SlicerVMTK/lib/Slicer-4.13/qt-loadable-modules/vtkvmtkSegmentationPython.so
./lib/Slicer-4.13/vtkvmtkCommonPython.so
./lib/Slicer-4.13/vtkvmtkComputationalGeometryPython.so
./lib/Slicer-4.13/vtkvmtkDifferentialGeometryPython.so
./lib/Slicer-4.13/vtkvmtkIOPython.so
./lib/Slicer-4.13/vtkvmtkITKPython.so
./lib/Slicer-4.13/vtkvmtkMiscPython.so
./lib/Slicer-4.13/vtkvmtkSegmentationPython.so
```

**Comment by lassoan** [comment]
Awesome, thank you! I'll test this later today to confirm that all is good.

**Comment by lassoan** [comment]
Thanks a lot @jcfr, VMTK now works perfectly on macOS!

**Comment by jcfr** [comment]
> VMTK now works perfectly on macOS!

Great. Thanks for testing :pray:

**Pull request merged**
