### PR TITLE
Merge changes from current Slicer extension

### PR DESCRIPTION
**Pull request by lassoan**
Currently Slicer uses my SlicerExtension-VMTK fork (https://github.com/lassoan/SlicerExtension-VMTK) for building the extension. It contains lots of fixes and improvements.

### CODE REVIEW

**Comment by lassoan** [comment]
I would be OK to take over maintenance of this extension here. Could I get write access to vmtk/SlicerExtension-VMTK?

**Comment by pieper** [comment]
Sounds good to me.  I think @lantiga needs to add you to the project.

**Comment by lantiga** [comment]
Hi, this is great. By all means, yes. I'll add you right now.

**Comment by lantiga** [comment]
Done, you can accept the invitation at https://github.com/vmtk

**Comment by lassoan** [comment]
Thank you!

**Comment by lantiga** [comment]
Thank *you* :-)

**Comment by lassoan** [comment]
I've updated the Slicer extension index to use latest master of vmtk/SlicerExtension-VMTK repository.

**Pull request merged**
