### PR TITLE
Updated CPack packaging in CMakeLists

### PR DESCRIPTION
**Pull request by mschumak**
The packaging section at the end of CMakeLists has been updated to follow the format of other Slicer extensions, e.g., 
https://github.com/openigtlink/SlicerOpenIGTLink/commit/da0bc5ce5c9a528da4f0a734c4bd099e579492d0
This provides access via the cache to the ${EXTENSION_NAME}_CPACK_INSTALL_CMAKE_PROJECTS list.
Also, the External_VMTK.cmake file now refers to a specific VMTK commit, rather than the master branch. This commit is the current master, so there will be no effect at this time.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks @mschumak . Looks good.

Few nitpick:
* the imperative is usually preferred in commit message. for example:

Instead of 

```
 Updated the packaging block dealing with CPack. Format follows, e.g., openigtlink/SlicerOpenIGTLink@da0bc5c
```

prefer

```
cpack: Update install rules to support bundling extension in custom app

This commit is adapted from openigtlink/SlicerOpenIGTLink@da0bc5c
```

I also suggest you squash all commits together.

**Comment by mschumak** [comment]
I also wanted to add VMTK dependence on ITK and VTK, but I do not know how to handle different VTK major versions. The VTK project in my Slicer build is VTKv9, but I didn't want to force that choice.
I found the need for this when I included the extension in a fresh superbuild of a custom Slicer application. Without the dependency, Make attempted to build VMTK before ITK, and the build failed.

**Comment by jcfr** [comment]
> The VTK project in my Slicer build is VTKv9, but I didn't want to force that choice.

You can always configure you custom app setting `Slicer_VTKv9_GIT_TAG` and `Slicer_VTKv9_GIT_REPOSITORY`. See [here](https://github.com/Slicer/Slicer/blob/e5a5efbe6a9982ee0dc8f12c45a35e1c96f6e617/SuperBuild/External_VTKv9.cmake#L117-L135)

While the name of the project is VTKv9, you can change the version. To pass other option, you would simply add : 

```
set(VTK_SOME_OPTION "bar")
mark_as_superbuild(VARS VTK_SOME_OPTION:STRING PROJECTS VTKv9)
```

> This should not happen

Since VMTK requires VTKv9 and ITKv4, a change similar to this one should be done in the extension: https://github.com/KitwareMedical/SlicerVirtualReality/commit/ce110b658622615a5607b5831538264d6133846e

**Comment by mschumak** [comment]
External_VMTK.cmake is updated based on the Slicer template for external sources, at github.com/Slicer/Slicer/blob/f08936e114b0cff769d6e4cb196d697848f29194/Utilities/Templates/Extensions/SuperBuild/SuperBuild/External_Foo.cmake#L23-L45.

Two problems continue with SlicerVMTK. The first relates to packaging for macOS, and was evident in the CDash page until Oct 1, 2018: http://slicer.cdash.org/index.php?project=SlicerPreview&date=2018-10-01&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=VMTK
The second relates to VTK changes made in Slicer started on Oct 1, 2018, and affect all platforms: 
http://slicer.cdash.org/index.php?project=SlicerPreview&date=2018-11-05&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=VMTK

**Comment by mschumak** [comment]
The External_VMTK.cmake in this PR now fetches the VMTK in https://github.com/lassoan/vmtk.git, at the commit that is currently the head of the fix-build-error-with-new-VTK-8-2 branch. This is a temporary location while that branch is waiting for a PR to vmtk/vmtk.git.

**Pull request merged**
