### PR TITLE
Add RAS point coordinates to centerline model table.

### PR DESCRIPTION
**Pull request by chir-set**
In addition to distance and diameter columns, three more columns R, A, S
are added, corresponding to the coordinates of each point of the
centerline model.

Following https://discourse.slicer.org/t/veselness-filter/17739

The user requesting this has not specified its usefullness. It seems harmless though.

### CODE REVIEW

**Review by lassoan — COMMENTED** [review]
This looks great, thank you!

Just two things would need to be improved:
- We use LPS coordinates in files. Could you add an option to choose between RAS and LPS coordinates?
- In most places we store coordinates in 3 components of a single vtkDoubleArray. You can keep the 3 separate arrays as an option.

**Comment by chir-set** [comment]
> * store coordinates in 3 components of a single vtkDoubleArray

You mean, one column with cell values as 

[-10.717971  18.031818 -83.89904 ]
[-10.72737   17.982111 -84.08649 ]
[-10.748347  17.931984 -84.34901 ]

?

**Comment by lassoan** [comment]
Yes, one vtkDoubleArray with number of components set to 3. For example, segment statistics module uses it for oriented bounding box position and orientation.

**Comment by chir-set** [comment]
> * We use LPS coordinates in files.
> * we store coordinates in 3 components of a single vtkDoubleArray. 

@lassoan 
Point coordinates are now presented in the table as LPS or RAS values, in 1 single or 3 separate columns.

It would be nice to fit the column width when presented in a single column, but I don't have a clue how to do that.

**Comment by lassoan** [comment]
Thank you! I've squashed and refactored the code a bit and merged it in https://github.com/vmtk/SlicerExtension-VMTK/commit/72a52b24b14ec70b03061e89075ab3cd018c30a6.

**Comment by chir-set** [comment]
> I've squashed and refactored the code a bit and merged it in [72a52b2](https://github.com/vmtk/SlicerExtension-VMTK/commit/72a52b24b14ec70b03061e89075ab3cd018c30a6).

@lassoan 
Sorry to bother yo again, but the 'Projected' mode is completely ignored following the refractoring. The table and plot are not updated in this mode, whichever axis is selected.

**Pull request closed without merging**
