### PR TITLE
Make most modules translatable

### PR DESCRIPTION
**Pull request by chir-set**
Hi @lassoan, @pieper,

This PR is intended to make most modules of SlicerVMTK translatable. It is based on branch 'ParameterNodeWrapperAndOther' which is in PR #107, and not on the 'master' branch.

The modifications follow [this](https://discourse.slicer.org/t/how-to-mark-some-strings-as-translatable/34008) discussion and the link to the [translation guide](https://github.com/Slicer/SlicerLanguagePacks/blob/main/DevelopersManual.md).

I don't claim this PR is 100% fit for a merge. Please advise about required improvements.

@lassoan, please note I have felt free to modify 'ExtractCenterline' module also in 2c40a32. This patch can be easily dropped if you deem it necessary.

This PR is intended to be merged in 'Rebase and merge' mode. If PR #107 is not accepted for a merge, I can still modify this PR to rebase it on 'master'.

Your comments are welcome.

Regards.

### CODE REVIEW

**Comment by pieper** [comment]
Thanks for working on this @chir-set 🙏 

@lassoan probably this is easiest to test by merging and looking on various computers, do you agree?  Or maybe you would rather read through the changes first.

**Comment by chir-set** [comment]
Hi @lassoan ,

Following your comment [here](https://discourse.slicer.org/t/how-to-mark-some-strings-as-translatable/34008/9?u=chir.set), what would you/I do with this PR?

Thank you for a follow-up.

**Review by lassoan — APPROVED** [review]
This looks great, thank you. I'll create the translation component on webmaster and then translations van be submitted there.

**Comment by chir-set** [comment]
Thanks for the merge @lassoan.

I translated an easy one for a first experience, ArterialCalcificationPreProcessor namely. I have no idea what happens next, how and when it is included at runtime. Please inform briefly. I can continue later on without any hurry.

Regards.

**Comment by lassoan** [comment]
You can now install the LanguagePacks extension, download translations, and select the application language. See https://github.com/Slicer/SlicerLanguagePacks/blob/main/HowToUse_fr.md

**Pull request merged**
